version: "3.8"

services:
  dev:
    build:
      args:
        - DEPLOYMENT_ENVIRONMENT=dev
      context: ./Docker/recommender
    container_name: recommender_dev
    env_file:
      - Docker/environment_variables/.env.dev
    ports:
      - "8888:8888"
    volumes:
      - ./:/usr/src/app

  staging:
    build:
      args:
        - DEPLOYMENT_ENVIRONMENT=staging
      context: Docker/recommender
    container_name: recommender_staging
    env_file:
      - Docker/environment_variables/.env.staging
    volumes:
      - ./:/usr/src/app

  prod:
    build:
      args:
        - DEPLOYMENT_ENVIRONMENT=prod
      context: Docker/recommender
    container_name: recommender_prod
    env_file:
      - Docker/environment_variables/.env.prod
#    environment:
#      - DEPLOYMENT_ENVIRONMENT=prod
    volumes:
      - ./:/usr/src/app

  db_staging:
    build:
      args:
        - DEPLOYMENT_ENVIRONMENT=staging
      context: Docker
      dockerfile: db/Dockerfile
    container_name: db_staging
    env_file:
      - Docker/environment_variables/.env.staging
#    environment:
#      - DEPLOYMENT_ENVIRONMENT=staging
    ports:
      - "5431:5432"
    volumes:
      - ./Docker/db/staging_data:/staging_data

  db_prod:
    build:
      args:
        - DEPLOYMENT_ENVIRONMENT=prod
      context: Docker
      dockerfile: db/Dockerfile
    container_name: db_prod
    env_file:
      - Docker/environment_variables/.env.prod
#    environment:
#      - DEPLOYMENT_ENVIRONMENT=prod
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/prod:/var/lib/postgresql/data