version: "3.8"

services:
  dev:
    build:
      args:
        - DEPLOYMENT_ENVIRONMENT=dev
      context: ./Docker/recommender
    container_name: recommender_dev
    env_file:
      - Docker/environment_variables/.env.dev
    ports:
      - "8888:8888"
    volumes:
      - ./:/usr/src/app

  stg:
    build:
      args:
        - DEPLOYMENT_ENVIRONMENT=stg
      context: Docker/recommender
    container_name: recommender_stg
    env_file:
      - Docker/environment_variables/.env.stg
    volumes:
      - ./:/usr/src/app

  prd:
    build:
      args:
        - DEPLOYMENT_ENVIRONMENT=prd
      context: Docker/recommender
    container_name: recommender_prd
    env_file:
      - Docker/environment_variables/.env.prd
    volumes:
      - ./:/usr/src/app

  db_stg:
    build:
      args:
        - DEPLOYMENT_ENVIRONMENT=stg
      context: Docker
      dockerfile: db/Dockerfile
    container_name: db_stg
    env_file:
      - Docker/environment_variables/.env.stg
    ports:
      - "5431:5432"
    volumes:
      - ./Docker/db/staging_data:/staging_data

  db_prd:
    build:
      args:
        - DEPLOYMENT_ENVIRONMENT=prd
      context: Docker
      dockerfile: db/Dockerfile
    container_name: db_prd
    env_file:
      - Docker/environment_variables/.env.prd
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/prd:/var/lib/postgresql/data